/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'deleteApiKey' : IDL.Func([IDL.Text], [], []),
  'getApiKey' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'isAdminPasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
  'listApiKeyNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'saveJarvisMessage' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setAdminPassword' : IDL.Func([IDL.Text], [], []),
  'setApiKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'deleteApiKey' : IDL.Func([IDL.Text], [], []),
    'getApiKey' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'isAdminPasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
    'listApiKeyNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'saveJarvisMessage' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setAdminPassword' : IDL.Func([IDL.Text], [], []),
    'setApiKey' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };